### ISSUE TITLE
MLS Salary Release Dates

### ISSUE THREAD

**Issue by kocraft** [American-Soccer-Analysis/asa-shiny-app#126]
Looks like every MLSPA release date is 2022-04-15 in the MLS salary data

**Comment by tyler-richardett** [comment]
Hey @kocraft, thanks for reaching out. If you open up the settings pane by clicking the gear icon in the top-right corner, you can use date or season selector to view historic MLSPA data. Screenshot below for reference.

<img width="1392" alt="Screen Shot 2022-06-14 at 3 43 03 PM" src="https://user-images.githubusercontent.com/29965912/173685881-0ac21ce0-0f2b-4097-9088-0069860f1292.png">

**Comment by kocraft** [comment]
ohh completely misunderstood what that field was, my bad!
