### ISSUE TITLE
Goals Added by pitch location?

### ISSUE THREAD

**Issue by tommyLIV** [American-Soccer-Analysis/asa-shiny-app#70]
I really like the ability to see xPasses by location. Would it be possible to filter G+ actions by third of the pitch they occur in? Is there something I'm missing? 

Love all the work, sorry if this is the wrong place to request this.

**Comment by MKullowatz** [comment]
That is a lovely request, posted in a lovely place. We are currently working on team g+ totals by very granular pitch zones, which is the next major feature, but we have added this to the backlog.

**Comment by tommyLIV** [comment]
Sounds great! Looking forward to it!

**Comment by kmx-stat** [comment]
any update here? Would love to see goals by location for an analysis on how penalty kicks affect the game. goals by location should help demonstrate areas of the box that are almost never scored from and an gap in expected goals from that spot to the PK can be calculated

**Comment by tyler-richardett** [comment]
Oops! Forgot to close out this issue. Resolved with #72.
![Screenshot 2023-01-12 at 1 44 03 PM](https://user-images.githubusercontent.com/29965912/212166085-53727e61-ed71-46ef-a4b0-19f5fdc46ec6.png)
